// Level data with specific tile color variations
const levels = [
  {
    characterInitialX: 9,
    characterInitialY: 7,
    levelData: [
      { tile: 'arrow', x: 6, y: 6, orientation: ORIENTATION_LEFT },
      { tile: 'rock', x: 7, y: 1 },
      { tile: 'flag', x: 9, y: 1 },
      { tile: 'rock', x: 11, y: 1 },
      { tile: 'rock', x: 7, y: 2 },
      { tile: 'rock', x: 11, y: 2 },
      { tile: 'rock', x: 1, y: 3 },
      { tile: 'rock', x: 2, y: 3 },
      { tile: 'rock', x: 3, y: 3 },
      { tile: 'rock', x: 4, y: 3 },
      { tile: 'rock', x: 5, y: 3 },
      { tile: 'rock', x: 6, y: 3 },
      { tile: 'rock', x: 7, y: 3 },
      { tile: 'block', x: 8, y: 3, orientation: ORIENTATION_LEFT },
      { tile: 'block', x: 9, y: 3, orientation: ORIENTATION_LEFT },
      {
        tile: 'block-trigger',
        x: 10,
        y: 3,
        orientation: ORIENTATION_LEFT,
      },
      { tile: 'lock', x: 11, y: 3 },
      { tile: 'rock', x: 12, y: 3 },
      { tile: 'rock', x: 13, y: 3 },
      { tile: 'rock', x: 14, y: 3 },
      { tile: 'rock', x: 15, y: 3 },
      { tile: 'rock', x: 16, y: 3 },
      { tile: 'rock', x: 17, y: 3 },
      { tile: 'rock', x: 18, y: 3 },
      { tile: 'rock', x: 6, y: 4 },
      { tile: 'gong-trigger', x: 3, y: 4 },
      { tile: 'arrow', x: 4, y: 4, orientation: ORIENTATION_LEFT },
      { tile: 'rock', x: 6, y: 4 },
      { tile: 'rock', x: 7, y: 4 },
      { tile: 'rock', x: 14, y: 4 },
      { tile: 'key', x: 15, y: 4 },
      { tile: 'rock', x: 16, y: 4 },
      { tile: 'rock', x: 1, y: 5 },
      { tile: 'rock', x: 2, y: 5 },
      { tile: 'rock', x: 3, y: 5 },
      { tile: 'rock', x: 4, y: 5 },
      { tile: 'rock', x: 7, y: 5 },
      { tile: 'rock', x: 14, y: 5 },
      // { tile: 'gong', x: 15, y: 5 },
      { tile: 'rock', x: 16, y: 5 },
      { tile: 'crate', x: 5, y: 6 },
      { tile: 'crate', x: 6, y: 6 },
      { tile: 'key-holder', x: 15, y: 4 },
      { tile: 'spawn-current', x: 9, y: 7 },
      { tile: 'arrow', x: 6, y: 7 },
    ],
  },
  {
    characterInitialX: 12,
    characterInitialY: 8,
    levelData: [
      { tile: 'rock', x: 11, y: 1 },
      {
        tile: 'block-trigger',
        x: 11,
        y: 2,
        orientation: ORIENTATION_RIGHT,
      },
      {
        tile: 'block',
        x: 12,
        y: 2,
        orientation: ORIENTATION_RIGHT,
      },
      {
        tile: 'block',
        x: 13,
        y: 2,
        orientation: ORIENTATION_DOWN,
      },
      { tile: 'rock', x: 11, y: 3 },
      {
        tile: 'block',
        x: 13,
        y: 3,
        orientation: ORIENTATION_DOWN,
      },
      { tile: 'rock', x: 5, y: 4 },
      { tile: 'spawn', x: 6, y: 4 },
      { tile: 'rock', x: 7, y: 4 },
      { tile: 'rock', x: 8, y: 4 },
      { tile: 'rock', x: 9, y: 4 },
      { tile: 'rock', x: 10, y: 4 },
      { tile: 'rock', x: 11, y: 4 },
      {
        tile: 'block',
        x: 13,
        y: 4,
        orientation: ORIENTATION_DOWN,
      },
      { tile: 'hole', x: 10, y: 5 },
      { tile: 'crate', x: 11, y: 5 },
      {
        tile: 'block',
        x: 13,
        y: 5,
        orientation: ORIENTATION_DOWN,
      },
      { tile: 'rock', x: 10, y: 6 },
      { tile: 'rock', x: 11, y: 6 },
      {
        tile: 'block',
        x: 13,
        y: 6,
        orientation: ORIENTATION_DOWN,
      },
      { tile: 'rock', x: 1, y: 7 },
      { tile: 'rock', x: 2, y: 7 },
      { tile: 'rock', x: 3, y: 7 },
      { tile: 'rock', x: 4, y: 7 },
      { tile: 'rock', x: 5, y: 7 },
      { tile: 'rock', x: 6, y: 7 },
      { tile: 'rock', x: 7, y: 7 },
      { tile: 'rock', x: 8, y: 7 },
      { tile: 'rock', x: 9, y: 7 },
      { tile: 'rock', x: 10, y: 7 },
      { tile: 'rock', x: 11, y: 7 },
      // { tile: 'gong', x: 12, y: 7 },
      { tile: 'rock', x: 13, y: 7 },
      { tile: 'flag', x: 16, y: 7 },
      { tile: 'gong-trigger', x: 1, y: 8 },
      { tile: 'trap', x: 7, y: 8 },
      { tile: 'trap', x: 8, y: 8 },
      { tile: 'trap', x: 9, y: 8 },
      { tile: 'trap', x: 10, y: 8 },
      { tile: 'trap', x: 11, y: 8 },
      { tile: 'spawn-current', x: 12, y: 8 },
      { tile: 'rock', x: 13, y: 8 },
    ],
  },
  {
    characterInitialX: 10,
    characterInitialY: 5,
    levelData: [],
  },
];
